.text
.code64

handler0:
	pushq $0;
	pushq $0;
	jmp start_handler;

handler1:
	pushq $0;
	pushq $1;
	jmp start_handler;

handler2:
	pushq $0;
	pushq $2;
	jmp start_handler;

handler3:
	pushq $0;
	pushq $3;
	jmp start_handler;

handler4:
	pushq $0;
	pushq $4;
	jmp start_handler;

handler5:
	pushq $0;
	pushq $5;
	jmp start_handler;

handler6:
	pushq $0;
	pushq $6;
	jmp start_handler;

handler7:
	pushq $0;
	pushq $7;
	jmp start_handler;

handler8:
	pushq $8;
	jmp start_handler;

handler9:
	pushq $0;
	pushq $9;
	jmp start_handler;

handler10:
	pushq $10;
	jmp start_handler;

handler11:
	pushq $11;
	jmp start_handler;

handler12:
	pushq $12;
	jmp start_handler;

handler13:
	pushq $13;
	jmp start_handler;

handler14:
	pushq $14;
	jmp start_handler;

handler15:
	pushq $0;
	pushq $15;
	jmp start_handler;

handler16:
	pushq $0;
	pushq $16;
	jmp start_handler;

handler17:
	pushq $17;
	jmp start_handler;

handler18:
	pushq $0;
	pushq $18;
	jmp start_handler;

handler19:
	pushq $0;
	pushq $19;
	jmp start_handler;

handler20:
	pushq $0;
	pushq $20;
	jmp start_handler;

handler21:
	pushq $0;
	pushq $21;
	jmp start_handler;

handler22:
	pushq $0;
	pushq $22;
	jmp start_handler;

handler23:
	pushq $0;
	pushq $23;
	jmp start_handler;

handler24:
	pushq $0;
	pushq $24;
	jmp start_handler;

handler25:
	pushq $0;
	pushq $25;
	jmp start_handler;

handler26:
	pushq $0;
	pushq $26;
	jmp start_handler;

handler27:
	pushq $0;
	pushq $27;
	jmp start_handler;

handler28:
	pushq $0;
	pushq $28;
	jmp start_handler;

handler29:
	pushq $0;
	pushq $29;
	jmp start_handler;

handler30:
	pushq $0;
	pushq $30;
	jmp start_handler;

handler31:
	pushq $0;
	pushq $31;
	jmp start_handler;

handler32:
	pushq $0;
	pushq $32;
	jmp start_handler;

handler33:
	pushq $0;
	pushq $33;
	jmp start_handler;

handler34:
	pushq $0;
	pushq $34;
	jmp start_handler;

handler35:
	pushq $0;
	pushq $35;
	jmp start_handler;

handler36:
	pushq $0;
	pushq $36;
	jmp start_handler;

handler37:
	pushq $0;
	pushq $37;
	jmp start_handler;

handler38:
	pushq $0;
	pushq $38;
	jmp start_handler;

handler39:
	pushq $0;
	pushq $39;
	jmp start_handler;

handler40:
	pushq $0;
	pushq $40;
	jmp start_handler;

handler41:
	pushq $0;
	pushq $41;
	jmp start_handler;

handler42:
	pushq $0;
	pushq $42;
	jmp start_handler;

handler43:
	pushq $0;
	pushq $43;
	jmp start_handler;

handler44:
	pushq $0;
	pushq $44;
	jmp start_handler;

handler45:
	pushq $0;
	pushq $45;
	jmp start_handler;

handler46:
	pushq $0;
	pushq $46;
	jmp start_handler;

handler47:
	pushq $0;
	pushq $47;
	jmp start_handler;

handler48:
	pushq $0;
	pushq $48;
	jmp start_handler;

handler49:
	pushq $0;
	pushq $49;
	jmp start_handler;

handler50:
	pushq $0;
	pushq $50;
	jmp start_handler;

handler51:
	pushq $0;
	pushq $51;
	jmp start_handler;

handler52:
	pushq $0;
	pushq $52;
	jmp start_handler;

handler53:
	pushq $0;
	pushq $53;
	jmp start_handler;

handler54:
	pushq $0;
	pushq $54;
	jmp start_handler;

handler55:
	pushq $0;
	pushq $55;
	jmp start_handler;

handler56:
	pushq $0;
	pushq $56;
	jmp start_handler;

handler57:
	pushq $0;
	pushq $57;
	jmp start_handler;

handler58:
	pushq $0;
	pushq $58;
	jmp start_handler;

handler59:
	pushq $0;
	pushq $59;
	jmp start_handler;

handler60:
	pushq $0;
	pushq $60;
	jmp start_handler;

handler61:
	pushq $0;
	pushq $61;
	jmp start_handler;

handler62:
	pushq $0;
	pushq $62;
	jmp start_handler;

handler63:
	pushq $0;
	pushq $63;
	jmp start_handler;

handler64:
	pushq $0;
	pushq $64;
	jmp start_handler;

handler65:
	pushq $0;
	pushq $65;
	jmp start_handler;

handler66:
	pushq $0;
	pushq $66;
	jmp start_handler;

handler67:
	pushq $0;
	pushq $67;
	jmp start_handler;

handler68:
	pushq $0;
	pushq $68;
	jmp start_handler;

handler69:
	pushq $0;
	pushq $69;
	jmp start_handler;

handler70:
	pushq $0;
	pushq $70;
	jmp start_handler;

handler71:
	pushq $0;
	pushq $71;
	jmp start_handler;

handler72:
	pushq $0;
	pushq $72;
	jmp start_handler;

handler73:
	pushq $0;
	pushq $73;
	jmp start_handler;

handler74:
	pushq $0;
	pushq $74;
	jmp start_handler;

handler75:
	pushq $0;
	pushq $75;
	jmp start_handler;

handler76:
	pushq $0;
	pushq $76;
	jmp start_handler;

handler77:
	pushq $0;
	pushq $77;
	jmp start_handler;

handler78:
	pushq $0;
	pushq $78;
	jmp start_handler;

handler79:
	pushq $0;
	pushq $79;
	jmp start_handler;

handler80:
	pushq $0;
	pushq $80;
	jmp start_handler;

handler81:
	pushq $0;
	pushq $81;
	jmp start_handler;

handler82:
	pushq $0;
	pushq $82;
	jmp start_handler;

handler83:
	pushq $0;
	pushq $83;
	jmp start_handler;

handler84:
	pushq $0;
	pushq $84;
	jmp start_handler;

handler85:
	pushq $0;
	pushq $85;
	jmp start_handler;

handler86:
	pushq $0;
	pushq $86;
	jmp start_handler;

handler87:
	pushq $0;
	pushq $87;
	jmp start_handler;

handler88:
	pushq $0;
	pushq $88;
	jmp start_handler;

handler89:
	pushq $0;
	pushq $89;
	jmp start_handler;

handler90:
	pushq $0;
	pushq $90;
	jmp start_handler;

handler91:
	pushq $0;
	pushq $91;
	jmp start_handler;

handler92:
	pushq $0;
	pushq $92;
	jmp start_handler;

handler93:
	pushq $0;
	pushq $93;
	jmp start_handler;

handler94:
	pushq $0;
	pushq $94;
	jmp start_handler;

handler95:
	pushq $0;
	pushq $95;
	jmp start_handler;

handler96:
	pushq $0;
	pushq $96;
	jmp start_handler;

handler97:
	pushq $0;
	pushq $97;
	jmp start_handler;

handler98:
	pushq $0;
	pushq $98;
	jmp start_handler;

handler99:
	pushq $0;
	pushq $99;
	jmp start_handler;

handler100:
	pushq $0;
	pushq $100;
	jmp start_handler;

handler101:
	pushq $0;
	pushq $101;
	jmp start_handler;

handler102:
	pushq $0;
	pushq $102;
	jmp start_handler;

handler103:
	pushq $0;
	pushq $103;
	jmp start_handler;

handler104:
	pushq $0;
	pushq $104;
	jmp start_handler;

handler105:
	pushq $0;
	pushq $105;
	jmp start_handler;

handler106:
	pushq $0;
	pushq $106;
	jmp start_handler;

handler107:
	pushq $0;
	pushq $107;
	jmp start_handler;

handler108:
	pushq $0;
	pushq $108;
	jmp start_handler;

handler109:
	pushq $0;
	pushq $109;
	jmp start_handler;

handler110:
	pushq $0;
	pushq $110;
	jmp start_handler;

handler111:
	pushq $0;
	pushq $111;
	jmp start_handler;

handler112:
	pushq $0;
	pushq $112;
	jmp start_handler;

handler113:
	pushq $0;
	pushq $113;
	jmp start_handler;

handler114:
	pushq $0;
	pushq $114;
	jmp start_handler;

handler115:
	pushq $0;
	pushq $115;
	jmp start_handler;

handler116:
	pushq $0;
	pushq $116;
	jmp start_handler;

handler117:
	pushq $0;
	pushq $117;
	jmp start_handler;

handler118:
	pushq $0;
	pushq $118;
	jmp start_handler;

handler119:
	pushq $0;
	pushq $119;
	jmp start_handler;

handler120:
	pushq $0;
	pushq $120;
	jmp start_handler;

handler121:
	pushq $0;
	pushq $121;
	jmp start_handler;

handler122:
	pushq $0;
	pushq $122;
	jmp start_handler;

handler123:
	pushq $0;
	pushq $123;
	jmp start_handler;

handler124:
	pushq $0;
	pushq $124;
	jmp start_handler;

handler125:
	pushq $0;
	pushq $125;
	jmp start_handler;

handler126:
	pushq $0;
	pushq $126;
	jmp start_handler;

handler127:
	pushq $0;
	pushq $127;
	jmp start_handler;

handler128:
	pushq $0;
	pushq $128;
	jmp start_handler;

handler129:
	pushq $0;
	pushq $129;
	jmp start_handler;

handler130:
	pushq $0;
	pushq $130;
	jmp start_handler;

handler131:
	pushq $0;
	pushq $131;
	jmp start_handler;

handler132:
	pushq $0;
	pushq $132;
	jmp start_handler;

handler133:
	pushq $0;
	pushq $133;
	jmp start_handler;

handler134:
	pushq $0;
	pushq $134;
	jmp start_handler;

handler135:
	pushq $0;
	pushq $135;
	jmp start_handler;

handler136:
	pushq $0;
	pushq $136;
	jmp start_handler;

handler137:
	pushq $0;
	pushq $137;
	jmp start_handler;

handler138:
	pushq $0;
	pushq $138;
	jmp start_handler;

handler139:
	pushq $0;
	pushq $139;
	jmp start_handler;

handler140:
	pushq $0;
	pushq $140;
	jmp start_handler;

handler141:
	pushq $0;
	pushq $141;
	jmp start_handler;

handler142:
	pushq $0;
	pushq $142;
	jmp start_handler;

handler143:
	pushq $0;
	pushq $143;
	jmp start_handler;

handler144:
	pushq $0;
	pushq $144;
	jmp start_handler;

handler145:
	pushq $0;
	pushq $145;
	jmp start_handler;

handler146:
	pushq $0;
	pushq $146;
	jmp start_handler;

handler147:
	pushq $0;
	pushq $147;
	jmp start_handler;

handler148:
	pushq $0;
	pushq $148;
	jmp start_handler;

handler149:
	pushq $0;
	pushq $149;
	jmp start_handler;

handler150:
	pushq $0;
	pushq $150;
	jmp start_handler;

handler151:
	pushq $0;
	pushq $151;
	jmp start_handler;

handler152:
	pushq $0;
	pushq $152;
	jmp start_handler;

handler153:
	pushq $0;
	pushq $153;
	jmp start_handler;

handler154:
	pushq $0;
	pushq $154;
	jmp start_handler;

handler155:
	pushq $0;
	pushq $155;
	jmp start_handler;

handler156:
	pushq $0;
	pushq $156;
	jmp start_handler;

handler157:
	pushq $0;
	pushq $157;
	jmp start_handler;

handler158:
	pushq $0;
	pushq $158;
	jmp start_handler;

handler159:
	pushq $0;
	pushq $159;
	jmp start_handler;

handler160:
	pushq $0;
	pushq $160;
	jmp start_handler;

handler161:
	pushq $0;
	pushq $161;
	jmp start_handler;

handler162:
	pushq $0;
	pushq $162;
	jmp start_handler;

handler163:
	pushq $0;
	pushq $163;
	jmp start_handler;

handler164:
	pushq $0;
	pushq $164;
	jmp start_handler;

handler165:
	pushq $0;
	pushq $165;
	jmp start_handler;

handler166:
	pushq $0;
	pushq $166;
	jmp start_handler;

handler167:
	pushq $0;
	pushq $167;
	jmp start_handler;

handler168:
	pushq $0;
	pushq $168;
	jmp start_handler;

handler169:
	pushq $0;
	pushq $169;
	jmp start_handler;

handler170:
	pushq $0;
	pushq $170;
	jmp start_handler;

handler171:
	pushq $0;
	pushq $171;
	jmp start_handler;

handler172:
	pushq $0;
	pushq $172;
	jmp start_handler;

handler173:
	pushq $0;
	pushq $173;
	jmp start_handler;

handler174:
	pushq $0;
	pushq $174;
	jmp start_handler;

handler175:
	pushq $0;
	pushq $175;
	jmp start_handler;

handler176:
	pushq $0;
	pushq $176;
	jmp start_handler;

handler177:
	pushq $0;
	pushq $177;
	jmp start_handler;

handler178:
	pushq $0;
	pushq $178;
	jmp start_handler;

handler179:
	pushq $0;
	pushq $179;
	jmp start_handler;

handler180:
	pushq $0;
	pushq $180;
	jmp start_handler;

handler181:
	pushq $0;
	pushq $181;
	jmp start_handler;

handler182:
	pushq $0;
	pushq $182;
	jmp start_handler;

handler183:
	pushq $0;
	pushq $183;
	jmp start_handler;

handler184:
	pushq $0;
	pushq $184;
	jmp start_handler;

handler185:
	pushq $0;
	pushq $185;
	jmp start_handler;

handler186:
	pushq $0;
	pushq $186;
	jmp start_handler;

handler187:
	pushq $0;
	pushq $187;
	jmp start_handler;

handler188:
	pushq $0;
	pushq $188;
	jmp start_handler;

handler189:
	pushq $0;
	pushq $189;
	jmp start_handler;

handler190:
	pushq $0;
	pushq $190;
	jmp start_handler;

handler191:
	pushq $0;
	pushq $191;
	jmp start_handler;

handler192:
	pushq $0;
	pushq $192;
	jmp start_handler;

handler193:
	pushq $0;
	pushq $193;
	jmp start_handler;

handler194:
	pushq $0;
	pushq $194;
	jmp start_handler;

handler195:
	pushq $0;
	pushq $195;
	jmp start_handler;

handler196:
	pushq $0;
	pushq $196;
	jmp start_handler;

handler197:
	pushq $0;
	pushq $197;
	jmp start_handler;

handler198:
	pushq $0;
	pushq $198;
	jmp start_handler;

handler199:
	pushq $0;
	pushq $199;
	jmp start_handler;

handler200:
	pushq $0;
	pushq $200;
	jmp start_handler;

handler201:
	pushq $0;
	pushq $201;
	jmp start_handler;

handler202:
	pushq $0;
	pushq $202;
	jmp start_handler;

handler203:
	pushq $0;
	pushq $203;
	jmp start_handler;

handler204:
	pushq $0;
	pushq $204;
	jmp start_handler;

handler205:
	pushq $0;
	pushq $205;
	jmp start_handler;

handler206:
	pushq $0;
	pushq $206;
	jmp start_handler;

handler207:
	pushq $0;
	pushq $207;
	jmp start_handler;

handler208:
	pushq $0;
	pushq $208;
	jmp start_handler;

handler209:
	pushq $0;
	pushq $209;
	jmp start_handler;

handler210:
	pushq $0;
	pushq $210;
	jmp start_handler;

handler211:
	pushq $0;
	pushq $211;
	jmp start_handler;

handler212:
	pushq $0;
	pushq $212;
	jmp start_handler;

handler213:
	pushq $0;
	pushq $213;
	jmp start_handler;

handler214:
	pushq $0;
	pushq $214;
	jmp start_handler;

handler215:
	pushq $0;
	pushq $215;
	jmp start_handler;

handler216:
	pushq $0;
	pushq $216;
	jmp start_handler;

handler217:
	pushq $0;
	pushq $217;
	jmp start_handler;

handler218:
	pushq $0;
	pushq $218;
	jmp start_handler;

handler219:
	pushq $0;
	pushq $219;
	jmp start_handler;

handler220:
	pushq $0;
	pushq $220;
	jmp start_handler;

handler221:
	pushq $0;
	pushq $221;
	jmp start_handler;

handler222:
	pushq $0;
	pushq $222;
	jmp start_handler;

handler223:
	pushq $0;
	pushq $223;
	jmp start_handler;

handler224:
	pushq $0;
	pushq $224;
	jmp start_handler;

handler225:
	pushq $0;
	pushq $225;
	jmp start_handler;

handler226:
	pushq $0;
	pushq $226;
	jmp start_handler;

handler227:
	pushq $0;
	pushq $227;
	jmp start_handler;

handler228:
	pushq $0;
	pushq $228;
	jmp start_handler;

handler229:
	pushq $0;
	pushq $229;
	jmp start_handler;

handler230:
	pushq $0;
	pushq $230;
	jmp start_handler;

handler231:
	pushq $0;
	pushq $231;
	jmp start_handler;

handler232:
	pushq $0;
	pushq $232;
	jmp start_handler;

handler233:
	pushq $0;
	pushq $233;
	jmp start_handler;

handler234:
	pushq $0;
	pushq $234;
	jmp start_handler;

handler235:
	pushq $0;
	pushq $235;
	jmp start_handler;

handler236:
	pushq $0;
	pushq $236;
	jmp start_handler;

handler237:
	pushq $0;
	pushq $237;
	jmp start_handler;

handler238:
	pushq $0;
	pushq $238;
	jmp start_handler;

handler239:
	pushq $0;
	pushq $239;
	jmp start_handler;

handler240:
	pushq $0;
	pushq $240;
	jmp start_handler;

handler241:
	pushq $0;
	pushq $241;
	jmp start_handler;

handler242:
	pushq $0;
	pushq $242;
	jmp start_handler;

handler243:
	pushq $0;
	pushq $243;
	jmp start_handler;

handler244:
	pushq $0;
	pushq $244;
	jmp start_handler;

handler245:
	pushq $0;
	pushq $245;
	jmp start_handler;

handler246:
	pushq $0;
	pushq $246;
	jmp start_handler;

handler247:
	pushq $0;
	pushq $247;
	jmp start_handler;

handler248:
	pushq $0;
	pushq $248;
	jmp start_handler;

handler249:
	pushq $0;
	pushq $249;
	jmp start_handler;

handler250:
	pushq $0;
	pushq $250;
	jmp start_handler;

handler251:
	pushq $0;
	pushq $251;
	jmp start_handler;

handler252:
	pushq $0;
	pushq $252;
	jmp start_handler;

handler253:
	pushq $0;
	pushq $253;
	jmp start_handler;

handler254:
	pushq $0;
	pushq $254;
	jmp start_handler;

handler255:
	pushq $0;
	pushq $255;
	jmp start_handler;

.global int_handler
int_handler:
	.quad handler0
    .quad handler1
    .quad handler2
    .quad handler3
    .quad handler4
    .quad handler5
    .quad handler6
    .quad handler7
    .quad handler8
    .quad handler9
    .quad handler10
    .quad handler11
    .quad handler12
    .quad handler13
    .quad handler14
    .quad handler15
    .quad handler16
    .quad handler17
    .quad handler18
    .quad handler19
    .quad handler20
    .quad handler21
    .quad handler22
    .quad handler23
    .quad handler24
    .quad handler25
    .quad handler26
    .quad handler27
    .quad handler28
    .quad handler29
    .quad handler30
    .quad handler31
    .quad handler32
    .quad handler33
    .quad handler34
    .quad handler35
    .quad handler36
    .quad handler37
    .quad handler38
    .quad handler39
    .quad handler40
    .quad handler41
    .quad handler42
    .quad handler43
    .quad handler44
    .quad handler45
    .quad handler46
    .quad handler47
    .quad handler48
    .quad handler49
    .quad handler50
    .quad handler51
    .quad handler52
    .quad handler53
    .quad handler54
    .quad handler55
    .quad handler56
    .quad handler57
    .quad handler58
    .quad handler59
    .quad handler60
    .quad handler61
    .quad handler62
    .quad handler63
    .quad handler64
    .quad handler65
    .quad handler66
    .quad handler67
    .quad handler68
    .quad handler69
    .quad handler70
    .quad handler71
    .quad handler72
    .quad handler73
    .quad handler74
    .quad handler75
    .quad handler76
    .quad handler77
    .quad handler78
    .quad handler79
    .quad handler80
    .quad handler81
    .quad handler82
    .quad handler83
    .quad handler84
    .quad handler85
    .quad handler86
    .quad handler87
    .quad handler88
    .quad handler89
    .quad handler90
    .quad handler91
    .quad handler92
    .quad handler93
    .quad handler94
    .quad handler95
    .quad handler96
    .quad handler97
    .quad handler98
    .quad handler99
    .quad handler100
    .quad handler101
    .quad handler102
    .quad handler103
    .quad handler104
    .quad handler105
    .quad handler106
    .quad handler107
    .quad handler108
    .quad handler109
    .quad handler110
    .quad handler111
    .quad handler112
    .quad handler113
    .quad handler114
    .quad handler115
    .quad handler116
    .quad handler117
    .quad handler118
    .quad handler119
    .quad handler120
    .quad handler121
    .quad handler122
    .quad handler123
    .quad handler124
    .quad handler125
    .quad handler126
    .quad handler127
    .quad handler128
    .quad handler129
    .quad handler130
    .quad handler131
    .quad handler132
    .quad handler133
    .quad handler134
    .quad handler135
    .quad handler136
    .quad handler137
    .quad handler138
    .quad handler139
    .quad handler140
    .quad handler141
    .quad handler142
    .quad handler143
    .quad handler144
    .quad handler145
    .quad handler146
    .quad handler147
    .quad handler148
    .quad handler149
    .quad handler150
    .quad handler151
    .quad handler152
    .quad handler153
    .quad handler154
    .quad handler155
    .quad handler156
    .quad handler157
    .quad handler158
    .quad handler159
    .quad handler160
    .quad handler161
    .quad handler162
    .quad handler163
    .quad handler164
    .quad handler165
    .quad handler166
    .quad handler167
    .quad handler168
    .quad handler169
    .quad handler170
    .quad handler171
    .quad handler172
    .quad handler173
    .quad handler174
    .quad handler175
    .quad handler176
    .quad handler177
    .quad handler178
    .quad handler179
    .quad handler180
    .quad handler181
    .quad handler182
    .quad handler183
    .quad handler184
    .quad handler185
    .quad handler186
    .quad handler187
    .quad handler188
    .quad handler189
    .quad handler190
    .quad handler191
    .quad handler192
    .quad handler193
    .quad handler194
    .quad handler195
    .quad handler196
    .quad handler197
    .quad handler198
    .quad handler199
    .quad handler200
    .quad handler201
    .quad handler202
    .quad handler203
    .quad handler204
    .quad handler205
    .quad handler206
    .quad handler207
    .quad handler208
    .quad handler209
    .quad handler210
    .quad handler211
    .quad handler212
    .quad handler213
    .quad handler214
    .quad handler215
    .quad handler216
    .quad handler217
    .quad handler218
    .quad handler219
    .quad handler220
    .quad handler221
    .quad handler222
    .quad handler223
    .quad handler224
    .quad handler225
    .quad handler226
    .quad handler227
    .quad handler228
    .quad handler229
    .quad handler230
    .quad handler231
    .quad handler232
    .quad handler233
    .quad handler234
    .quad handler235
    .quad handler236
    .quad handler237
    .quad handler238
    .quad handler239
    .quad handler240
    .quad handler241
    .quad handler242
    .quad handler243
    .quad handler244
    .quad handler245
    .quad handler246
    .quad handler247
    .quad handler248
    .quad handler249
    .quad handler250
    .quad handler251
    .quad handler252
    .quad handler253
    .quad handler254
    .quad handler255

start_handler:
	pushq %rdi
    
	movq 8(%rsp), %rdi 
    
	pushq %r9
	pushq %r10
	pushq %r11
	pushq %r12
	pushq %r13
	pushq %r14
	pushq %r15
	pushq %rax
	pushq %rbx
	pushq %rcx
	pushq %rdx
	pushq %rbp
	pushq %rsi
    
    cld
	call handler

    popq %rsi
    popq %rbp
    popq %rdx
    popq %rcx
    popq %rbx
    popq %rax
	popq %r15
    popq %r14
    popq %r13
    popq %r12
    popq %r11
    popq %r10
    popq %r9
    popq %rdi

    addq $16, %rsp
    
    iretq
